In [1]:
### DeepLearning and TensorFlow Fundamentals

#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.1


In [2]:
#Creating tensors with tf constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check the number of dimensions of tensor
scalar.ndim

0

In [5]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
#Check the dimension of vector
vector.ndim

1

In [7]:
#Create a matrix
matrix=tf.constant([
    [10,7],
    [7,10]
])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
#Check the dimension of matrix
matrix.ndim

2

In [10]:
#Create another matrix
another_matrix=tf.constant([
    [10.,7.],
    [3.,2.],
    [8.,9.]
], dtype=tf.float16) #Specifying datatype

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [16]:
#Let's create a tensor
tensor=tf.constant(
   [
       [
           [1,2,3],
           [4,5,6]
       ],
       [
           [7,8,9],
           [10,11,12]
       ],
       [
           [13,14,15],
           [16,17,18]
       ]
   ]
)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [17]:
tensor.ndim

3

In [19]:
#Creating tensor with tf.Variable
variable_tensor=tf.Variable([10,7])
unvariable_tensor=tf.constant([10,7])
variable_tensor,unvariable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [20]:
variable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [23]:
#Changing variable/changeable tensor
variable_tensor[0].assign(10)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [25]:
#Throws an Error!
unvariable_tensor[0].assign(6)
unvariable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Creating a random tansors

In [27]:
random_1=tf.random.Generator.from_seed(42) #Set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [28]:
random_2=tf.random.Generator.from_seed(42) #Set seed for reproducibility
random_2=random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [29]:
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in tensor

In [32]:
#Shuffle a tensor
not_shuffled=tf.constant(
    [
        [10,7],
        [3,4],
        [2,5]
    ]
)

not_shuffled.ndim

2

In [33]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [34]:
shuffled_tensor=tf.random.shuffle(
    not_shuffled, seed=None, name=None
)

shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

### Creating tensors from numpy arrays

In [36]:
tf.random.set_seed(10) #Global level seed
tf.random.shuffle(not_shuffled,seed=42) #Operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [37]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [38]:
tf.zeros(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [39]:
## Turning numpy arrays into tensors

import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [42]:
A=tf.constant(numpy_A,shape=(2,3,4))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### Getting information from tensors

In [44]:
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [50]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [51]:
#Get every attributes of our tensor

print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of dimension(rank): ",rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Elements along 0 axis: ",rank_4_tensor.shape[0])
print("Elements along last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor))

Datatype of every element:  <dtype: 'float32'>
Number of dimension(rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along 0 axis:  2
Elements along last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)


### Indexing and Expandimg tensor

In [52]:
#They can be indexed like python lists

#Get first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [53]:
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [54]:
# Create a rank 2 tensor

rank_2_tensor=tf.constant(
    [
       [10,7],
       [7,10]
    ]
)

rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [55]:
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [57]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [58]:
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]])>

In [59]:
#Returns a tensor with a length 1 axis inserted at index axis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]])>

In [60]:
tf.expand_dims(rank_2_tensor,axis=0) #Expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10]]])>

### Manipulating tensor with Tensor operations

In [61]:
tensor=tf.constant([[10,7],[3,4]])
tensor+10 #Original tensor will not be changed

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [62]:
tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [63]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [64]:
#Using tensorflow built in functions

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

### Matrix Multiplication with Tensors

In [65]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [66]:
tf.linalg.matmul(
    tensor,tensor
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [67]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [68]:
#Matrix multiplication tensor @ operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [69]:
tensor.shape

TensorShape([2, 2])

In [70]:
X=tf.constant(
[
    [1,2],
    [3,4],
    [5,6]
])

Y=tf.constant(
    [
        [7,8],
        [9,10],
        [11,12]
    ]
)

X.shape,Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [71]:
#Multiplying matrices X and Y of incompatible shapes
X @ Y

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [72]:
#Incompatible shapes detection using tensorflow's inbuilt matmul function
tf.linalg.matmul(
   X,Y
)

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [73]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [74]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [75]:
tf.reshape(Y,shape=(2,3))  # The original matrix remains unchanged

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [77]:
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [79]:
X.shape, tf.reshape(Y,shape=(2,3)).shape #Resulting matrix is of 3X3

(TensorShape([3, 2]), TensorShape([2, 3]))

In [80]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [81]:
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [86]:
# Perform dot operation on X and Y
print(X)
print(Y)
tf.tensordot(tf.transpose(X),Y,axes=1)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [87]:
#Perform matrix multplication with X and Y(reshaped)

tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [92]:
print("Normal Y: ")
print(Y,"\n")

print("Reshaped Y: ")
print(tf.reshape(Y,(2,3)),"\n")

print("Transposed Y: ")
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y: 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### Changing the datatype of tensor

In [93]:
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [94]:
C=tf.constant([1,7])
C.dtype

tf.int32

In [95]:
D=tf.cast(C,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>,
 tf.float16)

### Tensor aggregation

In [97]:
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [98]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [99]:
#Create a random tensor with values b/w 0 and 100 of size 50

E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([45,  1, 89, 70,  4, 50, 46, 85,  1, 94, 22, 69, 67, 76, 90, 33, 70,
       66, 73,  9, 92, 51, 83, 53, 50, 54, 29, 97, 19, 92, 88, 10, 18, 88,
        2, 67, 35, 86, 85, 20, 68, 37, 68, 35, 12, 50, 47, 93, 25, 25])>

In [100]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [101]:
#Finding the minimum

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [102]:
#Finding the maxmimum

tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [103]:
#Finding the mean

tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [104]:
#Finding the sum

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2639>

In [118]:
F=tf.cast(E,dtype=tf.float64)

tf.math.reduce_variance(F),tf.math.reduce_std(F)

(<tf.Tensor: shape=(), dtype=float64, numpy=882.3716000000001>,
 <tf.Tensor: shape=(), dtype=float64, numpy=29.70474036244047>)

In [108]:
#Finding the Variance
a = tf.constant([1, 2, 3, 4], dtype = tf.float64)

tf.math.reduce_variance(a)

<tf.Tensor: shape=(), dtype=float64, numpy=1.25>

In [109]:
#Finding the standard deviation
tf.math.reduce_std(a)

<tf.Tensor: shape=(), dtype=float64, numpy=1.118033988749895>

### Finding positional maximum and minimum of a tensor

In [120]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [122]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [123]:
#Index our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [124]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [125]:
#Check for equality
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [126]:
#Finf the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [127]:
#Index our minimum value position
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor

In [128]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [129]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [131]:
G_squeezed=tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One hot encoding tensors

In [134]:
some_list=[0,1,2,3]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [135]:
# Specifying custom values for one-hot encoding

tf.one_hot(some_list,depth=4,on_value="yo I love deep learning",off_value="I like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I like to dance',
        b'I like to dance', b'I like to dance'],
       [b'I like to dance', b'yo I love deep learning',
        b'I like to dance', b'I like to dance'],
       [b'I like to dance', b'I like to dance',
        b'yo I love deep learning', b'I like to dance'],
       [b'I like to dance', b'I like to dance', b'I like to dance',
        b'yo I love deep learning']], dtype=object)>

### Squaring,log,square root

In [136]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [137]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [140]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [143]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy arrays

In [145]:
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [146]:
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [147]:
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [149]:
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_j=tf.constant([3.,7.,10.])

numpy_J.dtype,tensor_j.dtype

(tf.float64, tf.float32)

### Finding access to GPU's

In [151]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]